### PR TITLE
Feature/add formula variable support

### PR DESCRIPTION
**Pull request by floradu88**
I wanted to add variable/placehodlers support. e.g. A1:A2 and pass those as params.

### CODE REVIEW

**Comment by stever** [comment]
Hi Florescu. Looks interesting. I have not really got around to dealing with ranges in this work. I've learned a bit more about some Excel functions that really need more information about the cell references too.

I haven't take too close a look at this. The syntax appears not to be Excel-compatible, so I'm not very sure about it. I suppose it depends on the objective of the library. I'm afraid I've neglected to progress it further here. I'd be interested to get a bit more info on how you intend to use it. Thanks.

**Comment by floradu88** [comment]
Hello Steve,

Range Expander is used to convert any existing ranges into csv values similar to excel implementation.

Some of the calculations are based on similar libraries implementation for calculations. For example stdev is based on STDEV.S in excel.

For most implementation you can copy paste it in excel, but due to actual implementation of the current library it cannot be 100% compatible.

Regards,
Radu

**Comment by stever** [comment]
Hi Radu

Hey, that sounds great. It doesn't need to be compatible. I was just curious.

**Comment by floradu88** [comment]
As per your other comment, I am planning to use this library in couple of both public and private projects and I will be implementing most of the things I need first, then will implement missing functionality

**Comment by stever** [comment]
Appreciated. I will also add to some missing functionality, at some time, perhaps soon. Cheers.

**Comment by stever** [comment]
ExcelRangeExpander is licensed under the GPL, and FormulaCS is MIT licensed. For this to be valid I would have to change the license of FormulaCS, which I'm not prepared to do. I'll need to remove this package unless you will change the license attached to it.

**Comment by floradu88** [comment]
Hey Steve, I can change the license of that package as that was created by me. 

Regards, Radu

**Comment by stever** [comment]
Thanks Radu. Any non-viral, but GPL-compatible license should be fine. Ideally MIT, or BSD or Apache or something like that. Cheers, Steve.

**Pull request merged**
